
// Code generated by MetaFFI. DO NOT EDIT.
// Host code for JavaExtractor.json
package JavaExtractor

import (
	"github.com/MetaFFI/lang-plugin-go/api"
	"github.com/MetaFFI/plugin-sdk/compiler/go/IDL"
	. "github.com/MetaFFI/lang-plugin-go/go-runtime"
)





var runtime *api.MetaFFIRuntime
var mod *api.MetaFFIModule

// Entities Callers








var VariableInfo_Name_caller func(...interface{}) ([]interface{}, error)


var VariableInfo_Type_caller func(...interface{}) ([]interface{}, error)


var VariableInfo_IsStatic_caller func(...interface{}) ([]interface{}, error)


var VariableInfo_IsFinal_caller func(...interface{}) ([]interface{}, error)







var ParameterInfo_Name_caller func(...interface{}) ([]interface{}, error)


var ParameterInfo_Type_caller func(...interface{}) ([]interface{}, error)







var MethodInfo_Name_caller func(...interface{}) ([]interface{}, error)


var MethodInfo_IsStatic_caller func(...interface{}) ([]interface{}, error)


var MethodInfo_Comment_caller func(...interface{}) ([]interface{}, error)


var MethodInfo_Parameters_caller func(...interface{}) ([]interface{}, error)


var MethodInfo_ReturnValue_caller func(...interface{}) ([]interface{}, error)







var ClassInfo_Name_caller func(...interface{}) ([]interface{}, error)


var ClassInfo_Comment_caller func(...interface{}) ([]interface{}, error)


var ClassInfo_Package_caller func(...interface{}) ([]interface{}, error)


var ClassInfo_Fields_caller func(...interface{}) ([]interface{}, error)


var ClassInfo_Methods_caller func(...interface{}) ([]interface{}, error)


var ClassInfo_Constructors_caller func(...interface{}) ([]interface{}, error)







var JavaInfo_Classes_caller func(...interface{}) ([]interface{}, error)








var JavaExtractor_extract_caller func(...interface{}) ([]interface{}, error)


var JavaExtractor_JavaExtractor_caller func(...interface{}) ([]interface{}, error)





func BindModuleToCode(modulePath string){
	runtime = api.NewMetaFFIRuntime("openjdk")
	err := runtime.LoadRuntimePlugin()
	if err != nil {
		panic(err)
	}

	mod, err = runtime.LoadModule(modulePath)
	if err != nil {
		panic(err)
	}

	// load functions
	loadFF := func(fpath string, params []IDL.MetaFFITypeInfo, retvals []IDL.MetaFFITypeInfo) (caller func(...interface{}) ([]interface{}, error)){
		var err error
		caller, err = mod.LoadWithAlias(fpath, params, retvals)
		if err != nil{ // failed
			panic(err)
		}
		return caller
	}

	
	
	
	
	

	
	
	VariableInfo_Name_caller = loadFF("class=java_extractor.VariableInfo,field=Name,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	VariableInfo_Type_caller = loadFF("class=java_extractor.VariableInfo,field=Type,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	VariableInfo_IsStatic_caller = loadFF("class=java_extractor.VariableInfo,field=IsStatic,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.BOOL, Alias: "", Type: 1024, Dimensions: 0 },})
	
	
	VariableInfo_IsFinal_caller = loadFF("class=java_extractor.VariableInfo,field=IsFinal,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.BOOL, Alias: "", Type: 1024, Dimensions: 0 },})
	
	
	
	
	
	
	ParameterInfo_Name_caller = loadFF("class=java_extractor.ParameterInfo,field=Name,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	ParameterInfo_Type_caller = loadFF("class=java_extractor.ParameterInfo,field=Type,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	
	
	
	
	MethodInfo_Name_caller = loadFF("class=java_extractor.MethodInfo,field=Name,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	MethodInfo_IsStatic_caller = loadFF("class=java_extractor.MethodInfo,field=IsStatic,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.BOOL, Alias: "", Type: 1024, Dimensions: 0 },})
	
	
	MethodInfo_Comment_caller = loadFF("class=java_extractor.MethodInfo,field=Comment,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	MethodInfo_Parameters_caller = loadFF("class=java_extractor.MethodInfo,field=Parameters,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "ParameterInfo", Type: 32768, Dimensions: 0 },})
	
	
	MethodInfo_ReturnValue_caller = loadFF("class=java_extractor.MethodInfo,field=ReturnValue,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "ParameterInfo", Type: 32768, Dimensions: 0 },})
	
	
	
	
	
	
	ClassInfo_Name_caller = loadFF("class=java_extractor.ClassInfo,field=Name,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	ClassInfo_Comment_caller = loadFF("class=java_extractor.ClassInfo,field=Comment,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	ClassInfo_Package_caller = loadFF("class=java_extractor.ClassInfo,field=Package,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },})
	
	
	ClassInfo_Fields_caller = loadFF("class=java_extractor.ClassInfo,field=Fields,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "VariableInfo", Type: 32768, Dimensions: 0 },})
	
	
	ClassInfo_Methods_caller = loadFF("class=java_extractor.ClassInfo,field=Methods,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "MethodInfo", Type: 32768, Dimensions: 0 },})
	
	
	ClassInfo_Constructors_caller = loadFF("class=java_extractor.ClassInfo,field=Constructors,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "MethodInfo", Type: 32768, Dimensions: 0 },})
	
	
	
	
	
	
	JavaInfo_Classes_caller = loadFF("class=java_extractor.JavaInfo,field=Classes,getter=true,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "ClassInfo", Type: 32768, Dimensions: 0 },})
	
	
	
	
	
	
	
	JavaExtractor_extract_caller = loadFF("callable=extract,class=java_extractor.JavaInfo,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "JavaInfo", Type: 32768, Dimensions: 0 },})
	
	
	JavaExtractor_JavaExtractor_caller = loadFF("callable=<init>,class=java_extractor.JavaExtractor,instance_required=true,metaffi_guest_lib=JavaExtractor.jar", []IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.STRING8, Alias: "", Type: 4096, Dimensions: 0 },},[]IDL.MetaFFITypeInfo{IDL.MetaFFITypeInfo{StringType: IDL.HANDLE, Alias: "", Type: 32768, Dimensions: 0 },})
	
	
	
}

func Free() error{
	return runtime.ReleaseRuntimePlugin()
}






// Code to call foreign functions in module JavaExtractor via XLLR



type VariableInfo struct{
	h Handle
}



func (this *VariableInfo) GetHandle() Handle{
	return this.h
}

func (this *VariableInfo) SetHandle(h Handle){
	this.h = h
}



func (this *VariableInfo) Name_Getter() (name string, err error){
	

	var res []interface{}
	
	res, err = VariableInfo_Name_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *VariableInfo) Type_Getter() (type__ string, err error){
	

	var res []interface{}
	
	res, err = VariableInfo_Type_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *VariableInfo) IsStatic_Getter() (IsStatic bool, err error){
	

	var res []interface{}
	
	res, err = VariableInfo_IsStatic_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(bool), nil
}




func (this *VariableInfo) IsFinal_Getter() (IsFinal bool, err error){
	

	var res []interface{}
	
	res, err = VariableInfo_IsFinal_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(bool), nil
}





type ParameterInfo struct{
	h Handle
}



func (this *ParameterInfo) GetHandle() Handle{
	return this.h
}

func (this *ParameterInfo) SetHandle(h Handle){
	this.h = h
}



func (this *ParameterInfo) Name_Getter() (name string, err error){
	

	var res []interface{}
	
	res, err = ParameterInfo_Name_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *ParameterInfo) Type_Getter() (type__ string, err error){
	

	var res []interface{}
	
	res, err = ParameterInfo_Type_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}





type MethodInfo struct{
	h Handle
}



func (this *MethodInfo) GetHandle() Handle{
	return this.h
}

func (this *MethodInfo) SetHandle(h Handle){
	this.h = h
}



func (this *MethodInfo) Name_Getter() (name string, err error){
	

	var res []interface{}
	
	res, err = MethodInfo_Name_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *MethodInfo) IsStatic_Getter() (IsStatic bool, err error){
	

	var res []interface{}
	
	res, err = MethodInfo_IsStatic_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(bool), nil
}




func (this *MethodInfo) Comment_Getter() (Comment string, err error){
	

	var res []interface{}
	
	res, err = MethodInfo_Comment_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *MethodInfo) Parameters_Getter() (Parameters []ParameterInfo, err error){
	

	var res []interface{}
	
	res, err = MethodInfo_Parameters_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].([]ParameterInfo), nil
}




func (this *MethodInfo) ReturnValue_Getter() (return_values ParameterInfo, err error){
	

	var res []interface{}
	
	res, err = MethodInfo_ReturnValue_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(ParameterInfo), nil
}





type ClassInfo struct{
	h Handle
}



func (this *ClassInfo) GetHandle() Handle{
	return this.h
}

func (this *ClassInfo) SetHandle(h Handle){
	this.h = h
}



func (this *ClassInfo) Name_Getter() (name string, err error){
	

	var res []interface{}
	
	res, err = ClassInfo_Name_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *ClassInfo) Comment_Getter() (Comment string, err error){
	

	var res []interface{}
	
	res, err = ClassInfo_Comment_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *ClassInfo) Package_Getter() (Package string, err error){
	

	var res []interface{}
	
	res, err = ClassInfo_Package_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].(string), nil
}




func (this *ClassInfo) Fields_Getter() (fields []VariableInfo, err error){
	

	var res []interface{}
	
	res, err = ClassInfo_Fields_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].([]VariableInfo), nil
}




func (this *ClassInfo) Methods_Getter() (methods []MethodInfo, err error){
	

	var res []interface{}
	
	res, err = ClassInfo_Methods_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].([]MethodInfo), nil
}




func (this *ClassInfo) Constructors_Getter() (constructors []MethodInfo, err error){
	

	var res []interface{}
	
	res, err = ClassInfo_Constructors_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].([]MethodInfo), nil
}





type JavaInfo struct{
	h Handle
}



func (this *JavaInfo) GetHandle() Handle{
	return this.h
}

func (this *JavaInfo) SetHandle(h Handle){
	this.h = h
}



func (this *JavaInfo) Classes_Getter() (classes []ClassInfo, err error){
	

	var res []interface{}
	
	res, err = JavaInfo_Classes_caller(this.h , )
	
	if err != nil{
		return
	}
	
	return res[0].([]ClassInfo), nil
}





type JavaExtractor struct{
	h Handle
}


func NewJavaExtractor( filename string) (instance *JavaExtractor, err error){
	

	var res []interface{}
	res, err = JavaExtractor_JavaExtractor_caller( filename)
	if err != nil{
		return
	}

	inst := &JavaExtractor{
		h: res[0].(Handle),
	}
	
	return inst, nil	
}


func (this *JavaExtractor) GetHandle() Handle{
	return this.h
}

func (this *JavaExtractor) SetHandle(h Handle){
	this.h = h
}



func (this *JavaExtractor) Extract() (info JavaInfo, err error){
	

	var res []interface{}
	
	res, err = JavaExtractor_extract_caller(this.h, )
	
	if err != nil{
		return
	}
	
	return res[0].(JavaInfo), nil
}




